import Sidebar from "@/components/layout/Sidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import DatabaseProvider from "@/components/DatabaseProvider";
// ...existing code...

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <DatabaseProvider>
          <div className="h-screen w-full flex flex-col bg-[#F7F7F7]">
            {/* Header */}
            <Header />
            <div className="flex flex-1 min-h-0">
              {/* Sidebar */}
              <Sidebar />
              {/* Main Content */}
              <div className="flex-1 relative min-h-0 overflow-auto">
                {/* Background Image */}
                <div 
                  className="absolute inset-0"
                  style={{ 
                    backgroundImage: 'url(/bg.png)', 
                    backgroundSize: 'cover', 
                    backgroundPosition: 'center', 
                    backgroundRepeat: 'no-repeat' 
                  }}
                />
                <div className="relative z-10 p-4 h-full">
                  {children}
                </div>
              </div>
            </div>
          </div>
        </DatabaseProvider>
      </body>
    </html>
  );
}
